name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cddl:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install cddl parse5
      - run: ./scripts/cddl/generate.js
      - run: |
          cat remote.cddl
          cat local.cddl
      - run: |
          npx cddl validate local.cddl
          npx cddl validate remote.cddl
