name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cddl:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install -g cddl
      - run: ./scripts/cddl/generate.js
      - run: cat index.cddl
      - run: cddl validate index.cddl
